# Postgres database

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: localhost
  database: hireables_development

test:
  <<: *default
  host: localhost
  database: hireables_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
