---
:verbose: true
:concurrency: 5
:timeout: 60
development:
  :concurrency: 50
staging:
  :concurrency: 5
production:
  :concurrency: 5
:queues:
  - default
  - [mailers, 1]
  - [urgent, 1]
  - [low_priority, 2]
